version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: elie
      POSTGRES_PASSWORD: elieb
      POSTGRES_DB: domain-analysis
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_USER=elie
      - POSTGRES_PASSWORD=elieb
      - POSTGRES_DB=domain-analysis
      - POSTGRES_PORT=5432
      
volumes:
  postgres-data:

